import fs from "node:fs/promises";
import path from "node:path";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const outputDir = path.resolve("D:/Personal Projects/stitch_omnistack_erp_pos/outputs/pharmacy-testing");
const outputPath = path.join(outputDir, "smartx-pharmacy-inventory-import.xlsx");
const checkedOn = new Date("2026-08-25T00:00:00+05:00");
const operationalNote = "Price is source-backed; stock, batch, barcode, and expiry fields are testing values.";

const rows = [
  {
    sku: "PHR-PAIN-001",
    name: "Panadol Tab 500mg 10's",
    category: "Pain & Fever",
    unitPrice: 40.0,
    warehouse: "Main Warehouse",
    inHand: 48,
    reserved: 3,
    reorderLevel: 15,
    isFavorite: "Yes",
    isQuickSale: "Yes",
    visualCode: "PAN500",
    barcode: "8906110000001",
    batchNo: "B250801",
    expiryDate: new Date("2027-09-30"),
    packSize: "10's",
    manufacturer: "GSK Consumer Healthcare",
    supplier: "GSK Consumer Healthcare",
    sourceUrl: "https://sehat.com.pk/products/Panadol-Tab-500mg-10%27s.html",
  },
  {
    sku: "PHR-PAIN-002",
    name: "Panadol Extend Tab 665mg 20's",
    category: "Pain & Fever",
    unitPrice: 121.62,
    warehouse: "Main Warehouse",
    inHand: 22,
    reserved: 1,
    reorderLevel: 8,
    isFavorite: "Yes",
    isQuickSale: "Yes",
    visualCode: "PAN665",
    barcode: "8906110000002",
    batchNo: "B250802",
    expiryDate: new Date("2028-01-31"),
    packSize: "20's",
    manufacturer: "GSK Consumer Healthcare",
    supplier: "GSK Consumer Healthcare",
    sourceUrl: "https://sehat.com.pk/products/Panadol-Extend-Tab-665mg-20%27s.html",
  },
  {
    sku: "PHR-PAIN-003",
    name: "Panadol Forte Susp 90ml",
    category: "Pain & Fever",
    unitPrice: 98.92,
    warehouse: "Main Warehouse",
    inHand: 18,
    reserved: 1,
    reorderLevel: 6,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "PANF90",
    barcode: "8906110000003",
    batchNo: "B250803",
    expiryDate: new Date("2027-12-31"),
    packSize: "90ml",
    manufacturer: "GSK Consumer Healthcare",
    supplier: "GSK Consumer Healthcare",
    sourceUrl: "https://sehat.com.pk/manufacturers/GSK-Consumer-Healthcare.html",
  },
  {
    sku: "PHR-PAIN-004",
    name: "Panadol Liq 160mg 120ml",
    category: "Pain & Fever",
    unitPrice: 134.06,
    warehouse: "Main Warehouse",
    inHand: 16,
    reserved: 0,
    reorderLevel: 5,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "PANL12",
    barcode: "8906110000004",
    batchNo: "B250804",
    expiryDate: new Date("2027-11-30"),
    packSize: "120ml",
    manufacturer: "GSK Consumer Healthcare",
    supplier: "GSK Consumer Healthcare",
    sourceUrl: "https://sehat.com.pk/manufacturers/GSK-Consumer-Healthcare.html?page=5",
  },
  {
    sku: "PHR-PAIN-005",
    name: "Brufen Tab 600mg 1x12's",
    category: "Pain & Fever",
    unitPrice: 64.42,
    warehouse: "Main Warehouse",
    inHand: 30,
    reserved: 2,
    reorderLevel: 10,
    isFavorite: "Yes",
    isQuickSale: "Yes",
    visualCode: "BRUF60",
    barcode: "8906110000005",
    batchNo: "B250805",
    expiryDate: new Date("2028-02-29"),
    packSize: "1x12's",
    manufacturer: "Abbott Laboratories (Pakistan) Ltd.",
    supplier: "Abbott Laboratories (Pakistan) Ltd.",
    sourceUrl: "https://sehat.com.pk/categories/Over-The-Counter-Drugs/Pain/?page=2",
  },
  {
    sku: "PHR-PAIN-006",
    name: "Ponstan Forte Tab 500mg 10's",
    category: "Pain & Fever",
    unitPrice: 43.29,
    warehouse: "Main Warehouse",
    inHand: 34,
    reserved: 2,
    reorderLevel: 12,
    isFavorite: "Yes",
    isQuickSale: "Yes",
    visualCode: "PON500",
    barcode: "8906110000006",
    batchNo: "B250806",
    expiryDate: new Date("2028-03-31"),
    packSize: "10's",
    manufacturer: "Pfizer Pakistan",
    supplier: "Pfizer Pakistan",
    sourceUrl: "https://sehat.com.pk/manufacturers/Pfizer-Pakistan-.html",
  },
  {
    sku: "PHR-PAIN-007",
    name: "Ponstan Tab 250mg 10's",
    category: "Pain & Fever",
    unitPrice: 25.72,
    warehouse: "Main Warehouse",
    inHand: 26,
    reserved: 1,
    reorderLevel: 10,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "PON250",
    barcode: "8906110000007",
    batchNo: "B250807",
    expiryDate: new Date("2027-10-31"),
    packSize: "10's",
    manufacturer: "Pfizer Pakistan",
    supplier: "Pfizer Pakistan",
    sourceUrl: "https://sehat.com.pk/manufacturers/Pfizer-Pakistan-.html",
  },
  {
    sku: "PHR-ANTB-001",
    name: "AUGMENTIN Tab 625mg 6's",
    category: "Antibiotic",
    unitPrice: 260.57,
    warehouse: "Main Warehouse",
    inHand: 14,
    reserved: 2,
    reorderLevel: 6,
    isFavorite: "Yes",
    isQuickSale: "Yes",
    visualCode: "AUG625",
    barcode: "8906110000008",
    batchNo: "B250808",
    expiryDate: new Date("2027-08-31"),
    packSize: "6's",
    manufacturer: "Glaxosmithkline Pakistan Limited",
    supplier: "Glaxosmithkline Pakistan Limited",
    sourceUrl: "https://sehat.com.pk/products/Augmentin-Tab-625mg-6%27s.html",
  },
  {
    sku: "PHR-ANTB-002",
    name: "Augmentin Susp 312.5mg/5ml 90ml",
    category: "Antibiotic",
    unitPrice: 356.33,
    warehouse: "Main Warehouse",
    inHand: 9,
    reserved: 1,
    reorderLevel: 4,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "AUGS90",
    barcode: "8906110000009",
    batchNo: "B250809",
    expiryDate: new Date("2027-07-31"),
    packSize: "90ml",
    manufacturer: "Glaxosmithkline",
    supplier: "Glaxosmithkline",
    sourceUrl: "https://sehat.com.pk/categories/Prescription-Drugs-/Infections/Bacterial-infections/Penicillins/",
  },
  {
    sku: "PHR-INF-001",
    name: "Flagyl Tab 400mg 10's",
    category: "Infection",
    unitPrice: 43.2,
    warehouse: "Main Warehouse",
    inHand: 20,
    reserved: 1,
    reorderLevel: 8,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "FLG400",
    barcode: "8906110000010",
    batchNo: "B250810",
    expiryDate: new Date("2028-04-30"),
    packSize: "10's",
    manufacturer: "Sanofi Aventis",
    supplier: "Sanofi Aventis",
    sourceUrl: "https://sehat.com.pk/products/Flagyl-Tab-400mg-10%27s.html",
  },
  {
    sku: "PHR-DIAB-001",
    name: "Glucophage XR Tab 500mg 3x10's",
    category: "Diabetes",
    unitPrice: 217.12,
    warehouse: "Main Warehouse",
    inHand: 24,
    reserved: 3,
    reorderLevel: 10,
    isFavorite: "Yes",
    isQuickSale: "Yes",
    visualCode: "GLU500",
    barcode: "8906110000011",
    batchNo: "B250811",
    expiryDate: new Date("2028-05-31"),
    packSize: "3x10's",
    manufacturer: "Martin Dow Pharmaceutical Limited",
    supplier: "Martin Dow Pharmaceutical Limited",
    sourceUrl: "https://sehat.com.pk/products/Glucophage-XR-Tab-500mg-3x10%27s.html",
  },
  {
    sku: "PHR-DIAB-002",
    name: "Glucophage XR Tab 750mg 3x10's",
    category: "Diabetes",
    unitPrice: 372.0,
    warehouse: "Main Warehouse",
    inHand: 18,
    reserved: 2,
    reorderLevel: 8,
    isFavorite: "Yes",
    isQuickSale: "Yes",
    visualCode: "GLU750",
    barcode: "8906110000012",
    batchNo: "B250812",
    expiryDate: new Date("2028-06-30"),
    packSize: "3x10's",
    manufacturer: "Martin Dow Pharmaceuticals (Pak) Ltd",
    supplier: "Martin Dow Pharmaceuticals (Pak) Ltd",
    sourceUrl: "https://sehat.com.pk/categories/Prescription-Drugs-/Diabetes/Oral-anti%252ddiabetics/Biguanides/",
  },
  {
    sku: "PHR-DIAB-003",
    name: "Glucophage XR Tab 1g 1x10-s",
    category: "Diabetes",
    unitPrice: 105.57,
    warehouse: "Main Warehouse",
    inHand: 22,
    reserved: 1,
    reorderLevel: 8,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "GLU1G",
    barcode: "8906110000013",
    batchNo: "B250813",
    expiryDate: new Date("2027-12-31"),
    packSize: "1x10-s",
    manufacturer: "Martin Dow Pharmaceuticals (Pak) Ltd",
    supplier: "Martin Dow Pharmaceuticals (Pak) Ltd",
    sourceUrl: "https://sehat.com.pk/manufacturers/Martin-Dow-Pharmaceuticals-%28Pak%29-Ltd-.html?page=3",
  },
  {
    sku: "PHR-CARD-001",
    name: "Rosuva Tab 10mg 10's",
    category: "Cardiology",
    unitPrice: 318.6,
    warehouse: "Main Warehouse",
    inHand: 15,
    reserved: 1,
    reorderLevel: 6,
    isFavorite: "Yes",
    isQuickSale: "Yes",
    visualCode: "ROS10",
    barcode: "8906110000014",
    batchNo: "B250814",
    expiryDate: new Date("2028-01-31"),
    packSize: "10's",
    manufacturer: "Wilson's Pharmaceuticals",
    supplier: "Wilson's Pharmaceuticals",
    sourceUrl: "https://sehat.com.pk/products/Rosuva-Tab-10mg-10%27s.html",
  },
  {
    sku: "PHR-CARD-002",
    name: "Rovista EZ 10 +10 mg 10's",
    category: "Cardiology",
    unitPrice: 425.5,
    warehouse: "Main Warehouse",
    inHand: 12,
    reserved: 1,
    reorderLevel: 5,
    isFavorite: "Yes",
    isQuickSale: "Yes",
    visualCode: "ROVEZ",
    barcode: "8906110000015",
    batchNo: "B250815",
    expiryDate: new Date("2028-02-28"),
    packSize: "10's",
    manufacturer: "Getz Pharma Pakistan (Pvt) Ltd",
    supplier: "Getz Pharma Pakistan (Pvt) Ltd",
    sourceUrl: "https://sehat.com.pk/products/Rovista-EZ-10-%252b10-mg-10%27s.html",
  },
  {
    sku: "PHR-CARD-003",
    name: "Sofvasc Tab 5mg 1x30's",
    category: "Cardiology",
    unitPrice: 356.84,
    warehouse: "Main Warehouse",
    inHand: 20,
    reserved: 1,
    reorderLevel: 7,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "SOFVSC",
    barcode: "8906110000016",
    batchNo: "B250816",
    expiryDate: new Date("2028-03-31"),
    packSize: "1x30's",
    manufacturer: "Wilson's Pharmaceuticals",
    supplier: "Wilson's Pharmaceuticals",
    sourceUrl: "https://sehat.com.pk/products/Sofvasc-Tab-5mg-1x30%27s.html",
  },
  {
    sku: "PHR-CARD-004",
    name: "Norvasc Tab 5mg 30's",
    category: "Cardiology",
    unitPrice: 460.48,
    warehouse: "Main Warehouse",
    inHand: 11,
    reserved: 1,
    reorderLevel: 5,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "NOR5",
    barcode: "8906110000017",
    batchNo: "B250817",
    expiryDate: new Date("2028-05-31"),
    packSize: "30's",
    manufacturer: "Pfizer Pakistan",
    supplier: "Pfizer Pakistan",
    sourceUrl: "https://sehat.com.pk/manufacturers/Pfizer-Pakistan-.html",
  },
  {
    sku: "PHR-GI-001",
    name: "Motilium Tab 10mg 10's",
    category: "Gastrointestinal",
    unitPrice: 108.37,
    warehouse: "Main Warehouse",
    inHand: 18,
    reserved: 1,
    reorderLevel: 8,
    isFavorite: "Yes",
    isQuickSale: "Yes",
    visualCode: "MOT10",
    barcode: "8906110000018",
    batchNo: "B250818",
    expiryDate: new Date("2027-11-30"),
    packSize: "10's",
    manufacturer: "Aspin Pharma formerly Janssen-Cilag",
    supplier: "Aspin Pharma formerly Janssen-Cilag",
    sourceUrl: "https://sehat.com.pk/categories/Prescription-Drugs-/Gastrointestinal-disorders-/Nausea-and-vomiting/",
  },
  {
    sku: "PHR-GI-002",
    name: "Motilium Susp 5mg/5ml 120ml",
    category: "Gastrointestinal",
    unitPrice: 133.65,
    warehouse: "Main Warehouse",
    inHand: 10,
    reserved: 1,
    reorderLevel: 4,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "MOTS12",
    barcode: "8906110000019",
    batchNo: "B250819",
    expiryDate: new Date("2027-10-31"),
    packSize: "120ml",
    manufacturer: "Aspin Pharma formerly Janssen-Cilag",
    supplier: "Aspin Pharma formerly Janssen-Cilag",
    sourceUrl: "https://sehat.com.pk/products/Motilium-Susp-120ml.html",
  },
  {
    sku: "PHR-GI-003",
    name: "Diatazox Tab 500mg 20's",
    category: "Gastrointestinal",
    unitPrice: 319.0,
    warehouse: "Main Warehouse",
    inHand: 8,
    reserved: 1,
    reorderLevel: 3,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "DIA500",
    barcode: "8906110000020",
    batchNo: "B250820",
    expiryDate: new Date("2028-04-30"),
    packSize: "20's",
    manufacturer: "Continental Pharmaceuticals",
    supplier: "Continental Pharmaceuticals",
    sourceUrl: "https://sehat.com.pk/categories/Prescription-Drugs-/Gastrointestinal-disorders-/Anti%252ddiarrheal/",
  },
  {
    sku: "PHR-RESP-001",
    name: "Ventolin Evohaler 100mcg 1's",
    category: "Respiratory",
    unitPrice: 1000.0,
    warehouse: "Main Warehouse",
    inHand: 6,
    reserved: 1,
    reorderLevel: 3,
    isFavorite: "Yes",
    isQuickSale: "Yes",
    visualCode: "VENTIN",
    barcode: "8906110000021",
    batchNo: "B250821",
    expiryDate: new Date("2028-07-31"),
    packSize: "1's",
    manufacturer: "Glaxosmithkline",
    supplier: "Glaxosmithkline",
    sourceUrl: "https://sehat.com.pk/categories/Prescription-Drugs-/Asthma/Inhalers/?page=2",
  },
  {
    sku: "PHR-RESP-002",
    name: "Ventolin Expectorant SF 120ml",
    category: "Respiratory",
    unitPrice: 68.81,
    warehouse: "Main Warehouse",
    inHand: 20,
    reserved: 2,
    reorderLevel: 8,
    isFavorite: "Yes",
    isQuickSale: "Yes",
    visualCode: "VENTEX",
    barcode: "8906110000022",
    batchNo: "B250822",
    expiryDate: new Date("2027-08-31"),
    packSize: "120ml",
    manufacturer: "Glaxosmithkline",
    supplier: "Glaxosmithkline",
    sourceUrl: "https://sehat.com.pk/categories/Prescription-Drugs-/Lungs/?page=3",
  },
  {
    sku: "PHR-RESP-003",
    name: "Ventolin Syp SF 120ml",
    category: "Respiratory",
    unitPrice: 77.53,
    warehouse: "Main Warehouse",
    inHand: 18,
    reserved: 1,
    reorderLevel: 6,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "VENTSF",
    barcode: "8906110000023",
    batchNo: "B250823",
    expiryDate: new Date("2027-09-30"),
    packSize: "120ml",
    manufacturer: "Glaxosmithkline",
    supplier: "Glaxosmithkline",
    sourceUrl: "https://sehat.com.pk/categories/Prescription-Drugs-/Lungs/?page=3",
  },
  {
    sku: "PHR-VIT-001",
    name: "CAC-1000 Plus Lemon Tab 20's",
    category: "Vitamins & Supplements",
    unitPrice: 550.0,
    warehouse: "Main Warehouse",
    inHand: 12,
    reserved: 1,
    reorderLevel: 4,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "CAC1K",
    barcode: "8906110000024",
    batchNo: "B250824",
    expiryDate: new Date("2028-08-31"),
    packSize: "20's",
    manufacturer: "GSK Consumer Healthcare",
    supplier: "GSK Consumer Healthcare",
    sourceUrl: "https://sehat.com.pk/products/CAC%252d1000-Plus-Lemon-Tab-20%27s.html",
  },
  {
    sku: "PHR-VIT-002",
    name: "Evion Cap 600mg 10's",
    category: "Vitamins & Supplements",
    unitPrice: 127.75,
    warehouse: "Main Warehouse",
    inHand: 25,
    reserved: 1,
    reorderLevel: 8,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "EVI600",
    barcode: "8906110000025",
    batchNo: "B250825",
    expiryDate: new Date("2028-09-30"),
    packSize: "10's",
    manufacturer: "Martin Dow Pharmaceuticals (Pak) Ltd",
    supplier: "Martin Dow Pharmaceuticals (Pak) Ltd",
    sourceUrl: "https://sehat.com.pk/products/Evion-Cap-600mg-10%27s.html",
  },
  {
    sku: "PHR-VIT-003",
    name: "Evion Cap 400mg 10x10's",
    category: "Vitamins & Supplements",
    unitPrice: 1078.0,
    warehouse: "Main Warehouse",
    inHand: 5,
    reserved: 0,
    reorderLevel: 2,
    isFavorite: "No",
    isQuickSale: "No",
    visualCode: "EVI400",
    barcode: "8906110000026",
    batchNo: "B250826",
    expiryDate: new Date("2028-10-31"),
    packSize: "10x10's",
    manufacturer: "Martin Dow Pharmaceuticals (Pak) Ltd",
    supplier: "Martin Dow Pharmaceuticals (Pak) Ltd",
    sourceUrl: "https://sehat.com.pk/manufacturers/Martin-Dow-Pharmaceuticals-%28Pak%29-Ltd-.html?page=16",
  },
  {
    sku: "PHR-COGH-001",
    name: "No Kuff Cough Syp 120ml",
    category: "Cough & Cold",
    unitPrice: 205.0,
    warehouse: "Main Warehouse",
    inHand: 10,
    reserved: 1,
    reorderLevel: 4,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "NOKUFF",
    barcode: "8906110000027",
    batchNo: "B250827",
    expiryDate: new Date("2027-07-31"),
    packSize: "120ml",
    manufacturer: "Scilife Pharma (Pvt) Ltd",
    supplier: "Scilife Pharma (Pvt) Ltd",
    sourceUrl: "https://sehat.com.pk/products/No-Kuff-Cough-Syp-120ml.html",
  },
  {
    sku: "PHR-COGH-002",
    name: "Cosome Syp 120ml",
    category: "Cough & Cold",
    unitPrice: 167.0,
    warehouse: "Main Warehouse",
    inHand: 12,
    reserved: 1,
    reorderLevel: 5,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "COSOME",
    barcode: "8906110000028",
    batchNo: "B250828",
    expiryDate: new Date("2027-08-31"),
    packSize: "120ml",
    manufacturer: "Martin Dow Pharmaceuticals (Pak) Ltd",
    supplier: "Martin Dow Pharmaceuticals (Pak) Ltd",
    sourceUrl: "https://sehat.com.pk/products/Cosome-Syp-120ml.html",
  },
  {
    sku: "PHR-COGH-003",
    name: "Pacific's Cough Mix 120ml",
    category: "Cough & Cold",
    unitPrice: 111.38,
    warehouse: "Main Warehouse",
    inHand: 14,
    reserved: 1,
    reorderLevel: 5,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "PACMIX",
    barcode: "8906110000029",
    batchNo: "B250829",
    expiryDate: new Date("2027-09-30"),
    packSize: "120ml",
    manufacturer: "Pacific Pharmaceuticals Ltd.",
    supplier: "Pacific Pharmaceuticals Ltd.",
    sourceUrl: "https://sehat.com.pk/products/Pacific%27s-Cough-Mix-120ml.html",
  },
  {
    sku: "PHR-ANTA-001",
    name: "DEACID Susp 120ml",
    category: "Antacid",
    unitPrice: 17.0,
    warehouse: "Main Warehouse",
    inHand: 30,
    reserved: 2,
    reorderLevel: 10,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "DEACID",
    barcode: "8906110000030",
    batchNo: "B250830",
    expiryDate: new Date("2028-01-31"),
    packSize: "120ml",
    manufacturer: "Delta Pharma (Pvt) Ltd. Pak",
    supplier: "Delta Pharma (Pvt) Ltd. Pak",
    sourceUrl: "https://sehat.com.pk/products/DEACID-Susp-120ml.html",
  },
  {
    sku: "PHR-INF-002",
    name: "Zetamax Tab 500mg 6's",
    category: "Infection",
    unitPrice: 358.61,
    warehouse: "Main Warehouse",
    inHand: 7,
    reserved: 1,
    reorderLevel: 3,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "ZETA50",
    barcode: "8906110000031",
    batchNo: "B250831",
    expiryDate: new Date("2028-04-30"),
    packSize: "6's",
    manufacturer: "Pfizer Pakistan",
    supplier: "Pfizer Pakistan",
    sourceUrl: "https://sehat.com.pk/manufacturers/Pfizer-Pakistan-.html",
  },
  {
    sku: "PHR-ANTI-001",
    name: "C-Nil Cap 400mg 10's",
    category: "Antiviral",
    unitPrice: 90.0,
    warehouse: "Main Warehouse",
    inHand: 9,
    reserved: 1,
    reorderLevel: 4,
    isFavorite: "No",
    isQuickSale: "Yes",
    visualCode: "CNIL40",
    barcode: "8906110000032",
    batchNo: "B250832",
    expiryDate: new Date("2028-06-30"),
    packSize: "10's",
    manufacturer: "Neomedix",
    supplier: "Neomedix",
    sourceUrl: "https://sehat.com.pk/categories/Prescription-Drugs-/Infections/Viral-infections/",
  },
];

const sourceNotes = [
  [
    "Source URL",
    "Coverage",
    "What is source-backed",
    "Freshness note",
    "Operational note",
  ],
  [
    "https://sehat.com.pk/products/Panadol-Tab-500mg-10%27s.html",
    "Single-product detail page",
    "Product name, pack size, manufacturer, and listed retail price",
    "Search snippet crawled about 2 weeks before 2026-08-25",
    "Use listed price as a testing reference; verify again before live billing.",
  ],
  [
    "https://sehat.com.pk/products/Panadol-Extend-Tab-665mg-20%27s.html",
    "Single-product detail page",
    "Product name, pack size, manufacturer, and listed retail price",
    "Search snippet crawled about 3 weeks before 2026-08-25",
    "Price field is source-backed; stock and batch fields are synthetic.",
  ],
  [
    "https://sehat.com.pk/manufacturers/GSK-Consumer-Healthcare.html",
    "Manufacturer listing page",
    "List price for Panadol Forte Susp 90ml and other GSK OTC items",
    "Search snippet crawled about 2 months before 2026-08-25",
    "Use as catalog-testing data, not a final procurement quote.",
  ],
  [
    "https://sehat.com.pk/manufacturers/GSK-Consumer-Healthcare.html?page=5",
    "Manufacturer listing page",
    "List price for Panadol Liq 160mg 120ml",
    "Search snippet crawled about 4 months before 2026-08-25",
    "Pricing may shift over time; re-check on deployment day.",
  ],
  [
    "https://sehat.com.pk/manufacturers/Pfizer-Pakistan-.html",
    "Manufacturer listing page",
    "List prices for Ponstan, Norvasc, and Zetamax rows",
    "Search snippet crawled about 1 month before 2026-08-25",
    "Retail price was kept real; warehouse quantities were generated for testing.",
  ],
  [
    "https://sehat.com.pk/categories/Prescription-Drugs-/Lungs/?page=3",
    "Category listing page",
    "List prices for Ventolin syrup and expectorant rows",
    "Search snippet crawled about 2 months before 2026-08-25",
    "Respiratory items are suitable for POS workflow testing only.",
  ],
  [
    "https://sehat.com.pk/categories/Prescription-Drugs-/Diabetes/Oral-anti%252ddiabetics/Biguanides/",
    "Category listing page",
    "List price for Glucophage XR 750mg 3x10's",
    "Search snippet crawled about 3 weeks before 2026-08-25",
    "Operational columns were normalized for app import.",
  ],
  [
    "https://sehat.com.pk/categories/Prescription-Drugs-/Gastrointestinal-disorders-/Anti%252ddiarrheal/",
    "Category listing page",
    "List price for Diatazox Tab 500mg 20's",
    "Search snippet crawled about 3 weeks before 2026-08-25",
    "Keep source URL in workbook when importing or sharing.",
  ],
  [
    "https://sehat.com.pk/categories/Prescription-Drugs-/Infections/Viral-infections/",
    "Category listing page",
    "List price for C-Nil Cap 400mg 10's",
    "Search snippet crawled about 9 months before 2026-08-25",
    "This is the oldest source in the workbook and should be rechecked first.",
  ],
];

await fs.mkdir(outputDir, { recursive: true });

const workbook = Workbook.create();
const importSheet = workbook.worksheets.add("Inventory Import");
const summarySheet = workbook.worksheets.add("Catalog Summary");
const notesSheet = workbook.worksheets.add("Source Notes");

importSheet.showGridLines = false;
summarySheet.showGridLines = false;
notesSheet.showGridLines = false;

const headers = [[
  "SKU",
  "Name",
  "Category",
  "Unit Price",
  "Warehouse",
  "In Hand",
  "Reserved",
  "Reorder Level",
  "Is Favorite",
  "Is Quick Sale",
  "Visual Code",
  "Barcode",
  "Batch No",
  "Expiry Date",
  "Pack Size",
  "Manufacturer",
  "Supplier",
  "Source URL",
  "Price Checked On",
  "Pricing Note",
  "Stock Value",
]];

const importValues = rows.map((row) => [
  row.sku,
  row.name,
  row.category,
  row.unitPrice,
  row.warehouse,
  row.inHand,
  row.reserved,
  row.reorderLevel,
  row.isFavorite,
  row.isQuickSale,
  row.visualCode,
  row.barcode,
  row.batchNo,
  row.expiryDate,
  row.packSize,
  row.manufacturer,
  row.supplier,
  row.sourceUrl,
  checkedOn,
  operationalNote,
  null,
]);

importSheet.getRange("A1:U1").values = headers;
importSheet.getRange(`A2:U${rows.length + 1}`).values = importValues;
importSheet.getRange(`U2:U${rows.length + 1}`).formulas = rows.map((_, index) => [`=D${index + 2}*F${index + 2}`]);

importSheet.getRange("A1:U1").format = {
  fill: "#0F3D5E",
  font: { bold: true, color: "#FFFFFF" },
  horizontalAlignment: "Center",
  verticalAlignment: "Center",
  wrapText: true,
  borders: { preset: "all", style: "thin", color: "#D7E3F0" },
};
importSheet.getRange(`A2:U${rows.length + 1}`).format = {
  borders: { preset: "all", style: "thin", color: "#E5EEF6" },
  verticalAlignment: "Center",
};
importSheet.getRange(`D2:D${rows.length + 1}`).format.numberFormat = '"PKR" #,##0.00';
importSheet.getRange(`U2:U${rows.length + 1}`).format.numberFormat = '"PKR" #,##0.00';
importSheet.getRange(`F2:H${rows.length + 1}`).format.numberFormat = "#,##0";
importSheet.getRange(`L2:L${rows.length + 1}`).format.numberFormat = "@";
importSheet.getRange(`N2:N${rows.length + 1}`).format.numberFormat = "yyyy-mm-dd";
importSheet.getRange(`S2:S${rows.length + 1}`).format.numberFormat = "yyyy-mm-dd";
importSheet.getRange(`R2:R${rows.length + 1}`).format.font = { color: "#1D4ED8", underline: "Single" };
importSheet.getRange(`T2:T${rows.length + 1}`).format.wrapText = true;
importSheet.getRange(`A2:U${rows.length + 1}`).conditionalFormats.add("expression", {
  formula: `=$F2<=$H2`,
  format: {
    fill: "#FFF7ED",
    font: { color: "#C2410C", bold: true },
  },
});
importSheet.freezePanes.freezeRows(1);

const importWidths = [
  16, 34, 20, 14, 18, 10, 10, 13, 11, 12, 12, 18, 14, 13, 14, 28, 28, 42, 16, 46, 14,
];
importWidths.forEach((width, index) => {
  importSheet.getRangeByIndexes(0, index, rows.length + 1, 1).format.columnWidth = width;
});
importSheet.getRange("A1:U1").format.rowHeight = 28;

summarySheet.getRange("A1:F1").merge();
summarySheet.getRange("A1").values = [["SmartX Pharmacy Test Catalog Summary"]];
summarySheet.getRange("A2:F2").merge();
summarySheet.getRange("A2").values = [[
  "This workbook is import-ready for the first sheet. Unit prices are source-backed from Pakistan pharmacy listings; stock, barcode, batch, and expiry fields were generated for testing.",
]];
summarySheet.getRange("A1:F2").format = {
  fill: "#0F172A",
  font: { color: "#FFFFFF", bold: true },
  verticalAlignment: "Center",
  wrapText: true,
};
summarySheet.getRange("A4:B9").values = [
  ["KPI", "Value"],
  ["Total SKUs", null],
  ["Total In-Hand Units", null],
  ["Reserved Units", null],
  ["Quick Sale Items", null],
  ["Retail Stock Value", null],
];
summarySheet.getRange("B5").formulas = [["=COUNTA('Inventory Import'!A2:A33)"]];
summarySheet.getRange("B6").formulas = [["=SUM('Inventory Import'!F2:F33)"]];
summarySheet.getRange("B7").formulas = [["=SUM('Inventory Import'!G2:G33)"]];
summarySheet.getRange("B8").formulas = [["=COUNTIF('Inventory Import'!J2:J33,\"Yes\")"]];
summarySheet.getRange("B9").formulas = [["=SUM('Inventory Import'!U2:U33)"]];
summarySheet.getRange("A4:B4").format = {
  fill: "#1D4ED8",
  font: { bold: true, color: "#FFFFFF" },
  borders: { preset: "all", style: "thin", color: "#D7E3F0" },
};
summarySheet.getRange("A5:B9").format = {
  borders: { preset: "all", style: "thin", color: "#D7E3F0" },
};
summarySheet.getRange("B9").format.numberFormat = '"PKR" #,##0.00';

summarySheet.getRange("D4:F14").values = [
  ["Category", "SKU Count", "Retail Value"],
  ["Pain & Fever", null, null],
  ["Antibiotic", null, null],
  ["Diabetes", null, null],
  ["Cardiology", null, null],
  ["Gastrointestinal", null, null],
  ["Respiratory", null, null],
  ["Vitamins & Supplements", null, null],
  ["Cough & Cold", null, null],
  ["Antacid", null, null],
  ["Antiviral", null, null],
];
const categoryRows = [
  "Pain & Fever",
  "Antibiotic",
  "Diabetes",
  "Cardiology",
  "Gastrointestinal",
  "Respiratory",
  "Vitamins & Supplements",
  "Cough & Cold",
  "Antacid",
  "Antiviral",
];
categoryRows.forEach((category, index) => {
  const rowNumber = index + 5;
  summarySheet.getRange(`E${rowNumber}`).formulas = [[`=COUNTIF('Inventory Import'!C2:C33,"${category}")`]];
  summarySheet.getRange(`F${rowNumber}`).formulas = [[`=SUMIF('Inventory Import'!C2:C33,"${category}",'Inventory Import'!U2:U33)`]];
});
summarySheet.getRange("D4:F4").format = {
  fill: "#1D4ED8",
  font: { bold: true, color: "#FFFFFF" },
  borders: { preset: "all", style: "thin", color: "#D7E3F0" },
};
summarySheet.getRange("D5:F14").format = {
  borders: { preset: "all", style: "thin", color: "#D7E3F0" },
};
summarySheet.getRange("F5:F14").format.numberFormat = '"PKR" #,##0.00';
summarySheet.getRange("A11:F11").merge();
summarySheet.getRange("A11").values = [["Testing Notes"]];
summarySheet.getRange("A12:B14").values = [
  ["1", "First worksheet remains the import worksheet because the API reads the first sheet in the uploaded xlsx."],
  ["2", "Operational fields like stock, batch, barcode, and expiry are intentionally synthetic to make testing realistic."],
  ["3", "Recheck prescription medicine prices before any production rollout because pharmacy prices can change."],
];
summarySheet.getRange("A11").format = {
  fill: "#DBEAFE",
  font: { bold: true, color: "#0F172A" },
};
summarySheet.getRange("A12:B14").format = {
  borders: { preset: "all", style: "thin", color: "#D7E3F0" },
  wrapText: true,
};
summarySheet.getRange("A1:F14").format.verticalAlignment = "Center";
summarySheet.getRange("A1:F14").format.autofitColumns();
summarySheet.getRange("A1:F14").format.autofitRows();
summarySheet.freezePanes.freezeRows(4);

notesSheet.getRange(`A1:E${sourceNotes.length}`).values = sourceNotes;
notesSheet.getRange("A1:E1").format = {
  fill: "#14532D",
  font: { bold: true, color: "#FFFFFF" },
  borders: { preset: "all", style: "thin", color: "#D7E3F0" },
};
notesSheet.getRange(`A2:E${sourceNotes.length}`).format = {
  borders: { preset: "all", style: "thin", color: "#D7E3F0" },
  wrapText: true,
  verticalAlignment: "Top",
};
notesSheet.getRange(`A2:A${sourceNotes.length}`).format.font = { color: "#1D4ED8", underline: "Single" };
["A", "B", "C", "D", "E"].forEach((column, index) => {
  const widths = [40, 24, 32, 28, 40];
  notesSheet.getRange(`${column}:${column}`).format.columnWidth = widths[index];
});
notesSheet.getRange(`A1:E${sourceNotes.length}`).format.autofitRows();
notesSheet.freezePanes.freezeRows(1);

const importInspect = await workbook.inspect({
  kind: "table",
  sheetId: "Inventory Import",
  range: "A1:U8",
  include: "values,formulas",
  tableMaxRows: 8,
  tableMaxCols: 21,
  maxChars: 5000,
});

const errorScan = await workbook.inspect({
  kind: "match",
  searchTerm: "#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",
  options: { useRegex: true, maxResults: 50 },
  summary: "final formula error scan",
  maxChars: 2000,
});

const importPreview = await workbook.render({
  sheetName: "Inventory Import",
  range: "A1:U20",
  scale: 1,
  format: "png",
});
await fs.writeFile(path.join(outputDir, "inventory-import-preview.png"), new Uint8Array(await importPreview.arrayBuffer()));

const summaryPreview = await workbook.render({
  sheetName: "Catalog Summary",
  range: "A1:F14",
  scale: 2,
  format: "png",
});
await fs.writeFile(path.join(outputDir, "catalog-summary-preview.png"), new Uint8Array(await summaryPreview.arrayBuffer()));

const notesPreview = await workbook.render({
  sheetName: "Source Notes",
  range: `A1:E${sourceNotes.length}`,
  scale: 1,
  format: "png",
});
await fs.writeFile(path.join(outputDir, "source-notes-preview.png"), new Uint8Array(await notesPreview.arrayBuffer()));

const xlsx = await SpreadsheetFile.exportXlsx(workbook);
await xlsx.save(outputPath);

console.log(JSON.stringify({
  outputPath,
  importInspect: importInspect.ndjson,
  errorScan: errorScan.ndjson,
  previewPaths: [
    path.join(outputDir, "inventory-import-preview.png"),
    path.join(outputDir, "catalog-summary-preview.png"),
    path.join(outputDir, "source-notes-preview.png"),
  ],
}, null, 2));
